
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Relative path (not just `ts-node`) so this resolves whether invoked
    // via `pnpm prisma db seed` (PATH includes node_modules/.bin) or by
    // calling the prisma binary directly, as the Docker `migrate` service
    // does to avoid pnpm 11's automatic deps-status-check side effect.
    seed: 'node_modules/.bin/ts-node --transpile-only prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
